version: '2'
services:
  haryanaagro-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/haryanaAgro/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=haryanaAgro
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
